---
title: "amcmc: A flexible MCMC estimation framework"
author: "George G. Vega Yon"
date: "April 19th, 2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{amcmc: A flexible MCMC estimation framework}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(amcmc)
data(logit, package = "mcmc")
out <- glm(y ~ x1 + x2 + x3 + x4, data = logit, family = binomial, x = TRUE)
beta.init <- as.numeric(coefficients(out))
```

```{r log-unnorm-posterior}
lupost_factory <- function(x, y) function(beta) {
    eta <- as.numeric(x %*% beta)
    logp <- ifelse(eta < 0, eta - log1p(exp(eta)), - log1p(exp(- eta)))
    logq <- ifelse(eta < 0, - log1p(exp(eta)), - eta - log1p(exp(- eta)))
    logl <- sum(logp[y == 1]) + sum(logq[y == 0])
    return(logl - sum(beta^2) / 8)
}

lupost <- lupost_factory(out$x, out$y)
```

```{r estimation}
# to get reproducible results
set.seed(42)
out1 <- MCMC(
  lupost,
  initial = beta.init,
  nsteps  = 1e4
)
```

```{r post-estimation, fig.dim=c(9, 9), out.width=600, out.height=600}
library(coda)
plot(out[,1:3])
```

```{r estimation2}
# to get reproducible results
set.seed(42)    
out <- MCMC(
  lupost,
  initial = beta.init,
  nsteps  = 1e4,
  kernel  = kernel_normal(scale = .5),
  )
```

```{r}
plot(out[,1:3])
```

```{r estimation3}
set.seed(42)
out <- MCMC(
  lupost,
  initial = beta.init,
  nsteps  = 2e4,
  kernel  = kernel_normal(scale = .5),
  thin    = 20
  )
```

So now we have reached convergence, thus, we can rerun the algorithm such that we start from the last step of the chain, this time, without convergence monitoring as the chains have forgotten their starting point.

```{r estimation4}
# Now we change the seed so we get a different stream of
# pseudo random numbers
set.seed(112) 

out_final <- MCMC(
  lupost, 
  initial = tail(out, 1),              # The last 2 points
  nsteps  = 5e4,                       # Increasing the sample size
  kernel  = kernel_normal(scale = .5),
  thin    = 20,
  nchains = 2L,
  multicore = TRUE,
  autostop = 0L
  )
```

```{r final-results}
plot(out_final[, 1:3])
```

