// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// normal_prop
NumericVector normal_prop(const NumericVector& x, const NumericVector& lb, const NumericVector& ub, const NumericVector& scale, const LogicalVector& fixed);
RcppExport SEXP _amcmc_normal_prop(SEXP xSEXP, SEXP lbSEXP, SEXP ubSEXP, SEXP scaleSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ub(ubSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_prop(x, lb, ub, scale, fixed));
    return rcpp_result_gen;
END_RCPP
}
// MCMC
NumericMatrix MCMC(Function& fun, const NumericVector& theta, int nbatch, const NumericVector& lb, const NumericVector& ub, const NumericVector& scale, const LogicalVector& fixed);
RcppExport SEXP _amcmc_MCMC(SEXP funSEXP, SEXP thetaSEXP, SEXP nbatchSEXP, SEXP lbSEXP, SEXP ubSEXP, SEXP scaleSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function& >::type fun(funSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type nbatch(nbatchSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ub(ubSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC(fun, theta, nbatch, lb, ub, scale, fixed));
    return rcpp_result_gen;
END_RCPP
}
// update_equal
NumericVector update_equal(const NumericVector& par, const std::vector< std::vector< unsigned int > >& ids);
RcppExport SEXP _amcmc_update_equal(SEXP parSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector< unsigned int > >& >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_equal(par, ids));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_amcmc_normal_prop", (DL_FUNC) &_amcmc_normal_prop, 5},
    {"_amcmc_MCMC", (DL_FUNC) &_amcmc_MCMC, 7},
    {"_amcmc_update_equal", (DL_FUNC) &_amcmc_update_equal, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_amcmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
