# file_version: 8ff13f4bcf8cc31b5275765494f542ca
# citer_version: 0.0.9000
# DO NOT EDIT THIS BY HAND!
# This document was automatically generated by the `citer` package.
# tools::md5sum()

# Citer Environment Setup
citation_on_load <- function() {

  pkg_name <- "fmcmc"
  
  packageStartupMessage(
    "Thank you for using ", pkg_name, "! ",
    "Please consider citing it in your work.\n",
    "You can find the citation information by running\n  citation(\"",
    pkg_name,
    "\")"
  )

}
.onLoad <- function(libname, pkgname) {
   citation_on_load()
 }
