# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_prop <- function(x, lb, ub, scale, fixed) {
    .Call('_amcmc_normal_prop', PACKAGE = 'amcmc', x, lb, ub, scale, fixed)
}

MCMCcpp <- function(fun, theta0, nbatch, lb, ub, scale, fixed) {
    .Call('_amcmc_MCMCcpp', PACKAGE = 'amcmc', fun, theta0, nbatch, lb, ub, scale, fixed)
}

update_equal <- function(par, ids) {
    .Call('_amcmc_update_equal', PACKAGE = 'amcmc', par, ids)
}

