cat("MATNAME=", Sys.getenv("MATNAME"), "\n", file = "envir.env")
cat("GITHUB_ACTION=", Sys.getenv("GITHUB_ACTION"), "\n", file = "envir.env", append = TRUE)
cat("GITHUB_REPOSITORY=", Sys.getenv("GITHUB_REPOSITORY"), "\n", file = "envir.env", append = TRUE)
cat("GITHUB_REF=", Sys.getenv("GITHUB_REF"), "\n", file = "envir.env", append = TRUE)
cat("GITHUB_HEAD_REF=", Sys.getenv("GITHUB_HEAD_REF"), "\n", file = "envir.env", append = TRUE)
cat("GITHUB_RUN_ID=", Sys.getenv("GITHUB_RUN_ID"), "\n", file = "envir.env", append = TRUE)
cat("GITHUB_SHA=", Sys.getenv("GITHUB_SHA"), "\n", file = "envir.env", append = TRUE)
cat("CODECOV_TOKEN=", Sys.getenv("CODECOV_TOKEN"), "\n", file = "envir.env", append = TRUE)
